/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts10120708;

import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author ZUP_92
 */
public class uts10120708 extends javax.swing.JFrame {

    /**
     * Creates new form uts10120708
     */
    public uts10120708() {
        initComponents();
        this.setTitle("10120708-Taufiq-UTS");
        txtJmlPahaAtas.setText("0");
        txtJmlPahaBawah.setText("0");
        txtJmlSayap.setText("0");
        txtJmlAti.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPembeli = new javax.swing.JTextField();
        boxPahaAtas = new javax.swing.JCheckBox();
        boxPahaBawah = new javax.swing.JCheckBox();
        boxSayap = new javax.swing.JCheckBox();
        boxAti = new javax.swing.JCheckBox();
        txtJmlPahaAtas = new javax.swing.JTextField();
        txtJmlSayap = new javax.swing.JTextField();
        txtJmlPahaBawah = new javax.swing.JTextField();
        txtJmlAti = new javax.swing.JTextField();
        boxLangsung = new javax.swing.JCheckBox();
        boxPesan = new javax.swing.JCheckBox();
        btnHitung = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaHasil = new javax.swing.JTextArea();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama Pembeli");

        jLabel2.setText("Jenis");

        jLabel3.setText("Jenis Pembelian");

        boxPahaAtas.setText("Paha Atas (RP. 5000)");

        boxPahaBawah.setText("Paha Bawah (Rp. 4500)");

        boxSayap.setText("Sayap (Rp. 2500)");

        boxAti.setText("Ati Ampela (Rp. 2000)");

        boxLangsung.setText("Langsung");

        boxPesan.setText("Pemesanan");

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        textAreaHasil.setColumns(20);
        textAreaHasil.setRows(5);
        jScrollPane1.setViewportView(textAreaHasil);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(boxPahaAtas)
                                    .addComponent(boxPahaBawah)
                                    .addComponent(boxSayap)
                                    .addComponent(boxAti))
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtJmlPahaAtas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtJmlPahaBawah, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtJmlSayap, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtJmlAti, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(boxLangsung)
                                    .addComponent(btnHitung))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnExit)
                                    .addComponent(boxPesan)))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(boxPahaAtas)
                        .addComponent(txtJmlPahaAtas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxPahaBawah)
                    .addComponent(txtJmlPahaBawah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtJmlSayap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxSayap))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxAti)
                    .addComponent(txtJmlAti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(boxLangsung)
                        .addComponent(boxPesan)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHitung)
                    .addComponent(btnExit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        //pilihan pesanan
  
        String pesan = "";
        
        if(boxPahaAtas.isSelected()){
            pesan += boxPahaAtas.getText() + " = " + txtJmlPahaAtas.getText() + 
                    "\n";
        }
        if(boxPahaBawah.isSelected()){
            pesan += boxPahaBawah.getText() + " = " + txtJmlPahaBawah.getText() + 
                    "\n";
        }
        if(boxSayap.isSelected()){
            pesan += boxSayap.getText() + " = " + txtJmlSayap.getText() + "\n";
        }
        if(boxAti.isSelected()){
            pesan += boxAti.getText() + " = " + txtJmlAti.getText() ;
        }
       

        //Validasi input
//        if(txtJmlPahaAtas.getText().equals("")){
//            JOptionPane.showMessageDialog(null, "Masukan jumlah pembelian "
//                    + "jika tidak ada isikan 0");
//        }
//        if(txtJmlPahaBawah.getText().equals("")) {
//            JOptionPane.showMessageDialog(null, "Masukan jumlah pembelian "
//                    + "jika tidak ada isikan 0");
//        }
//        if(txtJmlSayap.equals("")){
//            JOptionPane.showMessageDialog(null, "Masukan jumlah pembelian "
//                    + "jika tidak ada isikan 0");
//        }
//        if(txtJmlAti.equals("")){
//            JOptionPane.showMessageDialog(null, "Masukan jumlah pembelian "
//                    + "jika tidak ada isikan 0");
//        }
        
        //biaya subtotal
        double subtotal = Integer.parseInt(txtJmlPahaAtas.getText()) * 5000 + 
                Integer.parseInt(txtJmlPahaBawah.getText()) * 4500 +
                Integer.parseInt(txtJmlSayap.getText()) * 2500 +
               Integer.parseInt(txtJmlAti.getText()) * 2000;
        
        
        //potongan
        double potongan1 = 0;
        double potongan2 = 0;
        int a = Integer.parseInt(txtJmlPahaAtas.getText());
        int b = Integer.parseInt(txtJmlPahaBawah.getText());
        int c = Integer.parseInt(txtJmlSayap.getText());
        int d = Integer.parseInt(txtJmlAti.getText());
        
        
        if( a >= 5 || b >= 5){
            potongan1 = 0.05 * subtotal;
        }
        
        if( c >= 5 || d >= 5){
            potongan2 = 0.03 * subtotal;
        }
        
        double potongan = potongan1 + potongan2;
        //pesanan
        double ongkir = 0;
        
        if(boxPesan.isSelected()){
            ongkir =  0.05 * subtotal;
        }
        if(boxLangsung.isSelected()){
            ongkir =  0;
        }
        
        //pajak
        double pajak = 0.1 * subtotal;
        
        //Total Bayar
        double totalBayar =  subtotal - potongan + ongkir +pajak;
        
        
        //format rupiah
        Locale localeID = new Locale("in", "ID");
        NumberFormat formatRupiah = NumberFormat.getCurrencyInstance(localeID);

        // Tampil
        textAreaHasil.setText( textAreaHasil.getText()+ "DIKERJAKAN OLEH: " + 
                "\nNIM: 10120708" + "\nNAMA: Taufiq Qurohman Ruki" +
                "\nSEMESTER: 4" + "\nKELAS: IF-7" + "\n======================" +
                "\n" +
                "\nNama Pembeli: " + txtPembeli.getText() + 
                "\nSubtotal: " + pesan + "\nPotongan: " + 
                formatRupiah.format(potongan) + 
                "\nBiaya Pesan: " + formatRupiah.format(ongkir) + "\nPajak: " + 
                formatRupiah.format(pajak) +
                "\nTotal Bayar: " + formatRupiah.format( totalBayar));
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uts10120708.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uts10120708.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uts10120708.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uts10120708.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new uts10120708().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox boxAti;
    private javax.swing.JCheckBox boxLangsung;
    private javax.swing.JCheckBox boxPahaAtas;
    private javax.swing.JCheckBox boxPahaBawah;
    private javax.swing.JCheckBox boxPesan;
    private javax.swing.JCheckBox boxSayap;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAreaHasil;
    private javax.swing.JTextField txtJmlAti;
    private javax.swing.JTextField txtJmlPahaAtas;
    private javax.swing.JTextField txtJmlPahaBawah;
    private javax.swing.JTextField txtJmlSayap;
    private javax.swing.JTextField txtPembeli;
    // End of variables declaration//GEN-END:variables
}
